import Phaser from 'phaser';
import { Layout } from '../ui/Layout';import { Button } from '../ui/Button';import { DiceView } from '../ui/DiceView';import { StatusPanel } from '../ui/StatusPanel';import { BattleLogView } from '../ui/BattleLogView';
import { createState } from '../core/GameState';import { Random } from '../core/Random';import { rollAll, toggleLock, resetDiceTurn } from '../core/DiceRoller';import { resolveRunes } from '../core/CombatResolver';import { enemyAct, enemyIntent } from '../core/EnemyAI';import { ENEMY_ORDER } from '../data/enemies';import { applyReward, generateRewards } from '../core/RewardGenerator';
export class BattleScene extends Phaser.Scene{state=createState(Date.now());rng=new Random(this.state.seed);layout=new Layout();diceViews:DiceView[]=[];status!:StatusPanel;log!:BattleLogView;enemyText!:Phaser.GameObjects.Text;rerollBtn!:Button;settleBtn!:Button;rewardBtns:Button[]=[];
constructor(){super('Battle')}
create(){this.add.rectangle(195,422,390,844,0x0b1020);const r=this.layout.rects();this.enemyText=this.add.text(r.enemy.x,r.enemy.y,'',{fontSize:'24px',color:'#fff'});this.status=new StatusPanel(this,r.status.x,r.status.y);this.log=new BattleLogView(this,r.status.x,r.status.y+80);
this.state.dice.forEach((d,i)=>{const x=55+(i%5)*68,y=260;const v=new DiceView(this,d,x,y,()=>{if(this.state.phase!=='battle')return;toggleLock(d);this.renderAll();});this.diceViews.push(v)});
this.rerollBtn=new Button(this,110,560,150,54,'重掷',()=>this.onReroll());this.settleBtn=new Button(this,280,560,150,54,'结算',()=>this.onSettle());rollAll(this.state.dice,this.rng);this.renderAll();}
pushLog(s:string){this.state.log.push(s);console.log(s)}
onReroll(){if(this.state.player.rerollsLeft<=0||this.state.phase!=='battle')return;this.state.player.rerollsLeft--;rollAll(this.state.dice,this.rng);this.renderAll();}
onSettle(){if(this.state.phase!=='battle'||!this.state.enemy)return;resolveRunes(this.state.dice.map(d=>d.value),this.state.player,this.state.enemy,(s)=>this.pushLog(s));if(this.state.enemy.hp<=0){this.onEnemyDead();return;}enemyAct(this.state.enemy,this.state.player,this.state.dice,this.rng,(s)=>this.pushLog(s));if(this.state.player.hp<=0){this.state.phase='defeat';}else{resetDiceTurn(this.state.dice);this.state.player.rerollsLeft=this.state.player.rerollMax;this.state.enemy.intent=enemyIntent(this.state.enemy);rollAll(this.state.dice,this.rng);}this.renderAll();}
onEnemyDead(){this.state.battleIndex++;if(this.state.battleIndex>=ENEMY_ORDER.length){this.state.phase='victory';this.renderAll();return;}this.state.phase='reward';this.state.pendingRewards=generateRewards(this.state,this.rng);this.showRewards();}
showRewards(){this.rewardBtns.forEach(b=>{b.bg.destroy();b.txt.destroy()});this.rewardBtns=[];this.state.pendingRewards.forEach((rw,i)=>{const b=new Button(this,195,260+i*80,320,64,`${rw.name}: ${rw.desc}`,()=>{applyReward(this.state,rw);this.startNextBattle();});this.rewardBtns.push(b)});}
startNextBattle(){const def=ENEMY_ORDER[this.state.battleIndex];this.state.enemy={...def,hp:def.maxHp,armor:0,turn:1,intent:`Attack ${def.baseAttack}`};this.state.phase='battle';this.state.player.rerollsLeft=this.state.player.rerollMax;resetDiceTurn(this.state.dice);rollAll(this.state.dice,this.rng);this.rewardBtns.forEach(b=>{b.bg.destroy();b.txt.destroy()});this.rewardBtns=[];this.pushLog(`Next battle: ${def.name}`);this.renderAll();}
renderAll(){const e=this.state.enemy;this.enemyText.setText(this.state.phase==='victory'?'Victory!':this.state.phase==='defeat'?'Defeat!':`Enemy ${e?.name}\nHP ${e?.hp}/${e?.maxHp} ARM ${e?.armor}\nIntent: ${e?.intent}`);this.status.set(`HP ${this.state.player.hp}/${this.state.player.maxHp}  ARM ${this.state.player.armor}  GOLD ${this.state.player.gold}\nReroll ${this.state.player.rerollsLeft}/${this.state.player.rerollMax}\nRelics: ${this.state.player.relics.join(',')||'-'}`);this.log.set(this.state.log);this.diceViews.forEach(v=>v.render());this.rerollBtn.setEnabled(this.state.phase==='battle'&&this.state.player.rerollsLeft>0);this.settleBtn.setEnabled(this.state.phase==='battle');}
}
